training_data = [
    ("Hello", "Hi there!"),
    ("Hi", "Hello!"),
    ("Hey", "Hey! How can I assist you?"),
    ("Greetings", "Greetings! How can I help you?"),
    ("Howdy", "Hello! How can I assist you today?"),
    ("Good morning", "Good morning! How can I help you?"),
    ("Good afternoon", "Good afternoon! How may I assist you?"),
    ("Good evening", "Good evening! How can I assist you today?"),
    ("Yo", "Hey there! How can I assist you?"),
    ("What's up", "Hello! How can I help you today?"),
    ("Nice to meet you", "Likewise! How can I assist you?"),
    ("Hey there", "Hello! How can I help you today?"),
    ("Top of the morning to you", "And the rest of the day to you! How can I assist you?"),
    ("Hola", "Hola! ¿En qué puedo ayudarte hoy?"),
    ("Bonjour", "Bonjour! Comment puis-je t'aider aujourd'hui?"),
    ("Ciao", "Ciao! Come posso aiutarti oggi?"),
    ("Namaste", "Namaste! Aapki kaise madad kar sakta hoon?"),
    ("Salutations", "Salutations! How can I assist you?"),
    ("Hey friend", "Hello! How can I assist you today?"),
    ("Good to see you", "Good to see you too! How can I help you?"),
    ("Hey, how are you?", "Hi there! I'm here to assist you. How can I help you?"),
    ("Hello, how can I assist you today?", "Hi! What can I do for you today?"),
    ("Hi, how can I help you?", "Hello! How can I assist you today?"),
    ("Hey, how can I assist you?", "Hello! How can I help you today?"),
    ("Greetings, how can I assist you?", "Hello! How can I help you today?"),
    ("Good morning, how can I assist you?", "Good morning! How can I help you today?"),
    ("Good afternoon, how may I assist you?", "Good afternoon! How can I assist you?"),
    ("Good evening, how can I help you today?", "Good evening! How can I assist you today?"),
    ("Hi there, what can I do for you?", "Hello! How can I assist you today?"),
    ("Hey, how may I help you?", "Hello! How can I assist you today?"),
    ("Greetings, what can I do for you?", "Hello! How can I help you today?"),
    ("Howdy, how can I assist you?", "Hello! How can I help you today?"),
    ("Hi, how can I assist you today?", "Hello! How can I help you today?"),
    ("Hello there, how can I assist you?", "Hi! What can I do for you today?"),
    ("Hi, what brings you here today?", "Hello! How can I assist you today?"),
    ("Hey there, how may I help you?", "Hello! How can I assist you today?"),
    ("Greetings, how can I assist you?", "Hello! How can I help you today?"),
    ("Good morning, what can I do for you?", "Good morning! How can I help you today?"),
    ("Good afternoon, how can I assist you?", "Good afternoon! How can I assist you?"),
    ("Good evening, how can I help you today?", "Good evening! How can I assist you today?"),
    ("Hi there, what can I do for you?", "Hello! How can I assist you today?"),
    ("Hey, how may I help you?", "Hello! How can I assist you today?"),
    ("Greetings, what can I do for you?", "Hello! How can I help you today?"),
    ("Howdy, how can I assist you?", "Hello! How can I help you today?"),
    ("Hi, how can I assist you today?", "Hello! How can I help you today?"),
    ("Hello there, how can I assist you?", "Hi! What can I do for you today?"),
    ("Hi, what brings you here today?", "Hello! How can I assist you today?"),
    ("Hey there, how may I help you?", "Hello! How can I assist you today?"),
    ("Greetings, how can I assist you?", "Hello! How can I help you today?"),
    ("Good morning, what can I do for you?", "Good morning! How can I help you today?"),
    ("Good afternoon, how can I assist you?", "Good afternoon! How can I assist you?"),
    ("Good evening, how can I help you today?", "Good evening! How can I assist you today?"),
    ("Hi there, what can I do for you?", "Hello! How can I assist you today?"),
    ("Hey, how may I help you?", "Hello! How can I assist you today?"),
    ("Greetings, what can I do for you?", "Hello! How can I help you today?"),
    ("Howdy, how can I assist you?", "Hello! How can I help you today?"),
    ("Hi, how can I assist you today?", "Hello! How can I help you today?"),
    ("Hello there, how can I assist you?", "Hi! What can I do for you today?"),
    ("Hi, what brings you here today?", "Hello! How can I assist you today?"),
    ("Hey there, how may I help you?", "Hello! How can I assist you today?"),
    ("Greetings, how can I assist you?", "Hello! How can I help you today?"),
    ("Good morning, what can I do for you?", "Good morning! How can I help you today?"),
    ("Good afternoon, how can I assist you?", "Good afternoon! How can I assist you?"),
    ("Good evening, how can I help you today?", "Good evening! How can I assist you today?"),
]
